//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphAlgorithmsConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphAlgorithmsConsole.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\WGANOBIS\Documents\Praca magisterska\1000D.json.
        /// </summary>
        internal static string Main_GraphPath_1000D {
            get {
                return ResourceManager.GetString("Main_GraphPath_1000D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\WGANOBIS\Documents\Praca magisterska\1000N.json.
        /// </summary>
        internal static string Main_GraphPath_1000N {
            get {
                return ResourceManager.GetString("Main_GraphPath_1000N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\WGANOBIS\Documents\Praca magisterska\1000S.json.
        /// </summary>
        internal static string Main_GraphPath_1000S {
            get {
                return ResourceManager.GetString("Main_GraphPath_1000S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\WGANOBIS\Documents\Praca magisterska\graf_big.json.
        /// </summary>
        internal static string Main_GraphPath_20 {
            get {
                return ResourceManager.GetString("Main_GraphPath_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\WGANOBIS\Documents\Praca magisterska\2000D.json.
        /// </summary>
        internal static string Main_GraphPath_2000D {
            get {
                return ResourceManager.GetString("Main_GraphPath_2000D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\WGANOBIS\Documents\Praca magisterska\2000N.json.
        /// </summary>
        internal static string Main_GraphPath_2000N {
            get {
                return ResourceManager.GetString("Main_GraphPath_2000N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\WGANOBIS\Documents\Praca magisterska\2000S.json.
        /// </summary>
        internal static string Main_GraphPath_2000S {
            get {
                return ResourceManager.GetString("Main_GraphPath_2000S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\WGANOBIS\Documents\Praca magisterska\500D.json.
        /// </summary>
        internal static string Main_GraphPath_500D {
            get {
                return ResourceManager.GetString("Main_GraphPath_500D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\WGANOBIS\Documents\Praca magisterska\500N.json.
        /// </summary>
        internal static string Main_GraphPath_500N {
            get {
                return ResourceManager.GetString("Main_GraphPath_500N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\WGANOBIS\Documents\Praca magisterska\500S.json.
        /// </summary>
        internal static string Main_GraphPath_500S {
            get {
                return ResourceManager.GetString("Main_GraphPath_500S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------.
        /// </summary>
        internal static string PrintTimeResults_Line {
            get {
                return ResourceManager.GetString("PrintTimeResults_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas bellmanFordAdjacencyList: .
        /// </summary>
        internal static string PrintTimeResults_TimeBellmanFordAdjacencyList {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeBellmanFordAdjacencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas bellmanFordAdjacencyMatrix: .
        /// </summary>
        internal static string PrintTimeResults_TimeBellmanFordAdjacencyMatrix {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeBellmanFordAdjacencyMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas bellmanFordEdgeList: .
        /// </summary>
        internal static string PrintTimeResults_TimeBellmanFordEdgeList {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeBellmanFordEdgeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas bellmanFordVertexGraph: .
        /// </summary>
        internal static string PrintTimeResults_TimeBellmanFordVertexGraph {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeBellmanFordVertexGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas bfsAdjacencyList: .
        /// </summary>
        internal static string PrintTimeResults_TimeBfsAdjacencyList {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeBfsAdjacencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas bfsAdjacencyMatrix: .
        /// </summary>
        internal static string PrintTimeResults_TimeBfsAdjacencyMatrix {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeBfsAdjacencyMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas bfsEdgeList: .
        /// </summary>
        internal static string PrintTimeResults_TimeBfsEdgeList {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeBfsEdgeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas bfsBfsVertexGraph: .
        /// </summary>
        internal static string PrintTimeResults_TimeBfsVertexGraph {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeBfsVertexGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas boruvkaAdjacencyList: .
        /// </summary>
        internal static string PrintTimeResults_TimeBoruvkaAdjacencyList {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeBoruvkaAdjacencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas boruvkaAdjacencyMatrix: .
        /// </summary>
        internal static string PrintTimeResults_TimeBoruvkaAdjacencyMatrix {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeBoruvkaAdjacencyMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas boruvkaAEdgeList: .
        /// </summary>
        internal static string PrintTimeResults_TimeBoruvkaEdgeList {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeBoruvkaEdgeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas boruvkaVertexGraph: .
        /// </summary>
        internal static string PrintTimeResults_TimeBoruvkaVertexGraph {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeBoruvkaVertexGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas dfsAdjacencyList: .
        /// </summary>
        internal static string PrintTimeResults_TimeDfsAdjacencyList {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeDfsAdjacencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas dfsAdjacencyMatrix: .
        /// </summary>
        internal static string PrintTimeResults_TimeDfsAdjacencyMatrix {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeDfsAdjacencyMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas dfsEdgeList: .
        /// </summary>
        internal static string PrintTimeResults_TimeDfsEdgeList {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeDfsEdgeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas dfsDfsVertexGraph: .
        /// </summary>
        internal static string PrintTimeResults_TimeDfsTertexGraph {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeDfsTertexGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas dijkstraAdjacencyList: .
        /// </summary>
        internal static string PrintTimeResults_TimeDijkstraAdjacencyList {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeDijkstraAdjacencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas dijkstraAdjacencyMatrix: .
        /// </summary>
        internal static string PrintTimeResults_TimeDijkstraAdjacencyMatrix {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeDijkstraAdjacencyMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas dijkstraEdgeList: .
        /// </summary>
        internal static string PrintTimeResults_TimeDijkstraEdgeList {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeDijkstraEdgeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas dijkstraVertexGraph: .
        /// </summary>
        internal static string PrintTimeResults_TimeDijkstraVertexGraph {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeDijkstraVertexGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas kruskalAdjacencyList: .
        /// </summary>
        internal static string PrintTimeResults_TimeKruskalAdjacencyList {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeKruskalAdjacencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas kruskalAdjacencyMatrix: .
        /// </summary>
        internal static string PrintTimeResults_TimeKruskalAdjacencyMatrix {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeKruskalAdjacencyMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas kruskalEdgeList: .
        /// </summary>
        internal static string PrintTimeResults_TimeKruskalEdgeList {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeKruskalEdgeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas kruskalVertexGraph: .
        /// </summary>
        internal static string PrintTimeResults_TimeKruskalVertexGraph {
            get {
                return ResourceManager.GetString("PrintTimeResults_TimeKruskalVertexGraph", resourceCulture);
            }
        }
    }
}
