//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace graphConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("graphConverter.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane w pliku JSON - błędna macierz sąsiedctwa.
        /// </summary>
        internal static string ConverterAdjacencyMatrix_JsonToGraph_WrongArray {
            get {
                return ResourceManager.GetString("ConverterAdjacencyMatrix_JsonToGraph_WrongArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane w pliku JSON - nie można zlokalizować &quot;matrix&quot;.
        /// </summary>
        internal static string ConverterAdjacencyMatrix_JsonToGraph_WrongData {
            get {
                return ResourceManager.GetString("ConverterAdjacencyMatrix_JsonToGraph_WrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane w pliku JSON - nie można zlokalizować &quot;destination&quot; krawędzi.
        /// </summary>
        internal static string ConverterAjdacencyList_JsonToGraph_WrongDestination {
            get {
                return ResourceManager.GetString("ConverterAjdacencyList_JsonToGraph_WrongDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane w pliku JSON - nie można zlokalizować &quot;edge&quot;.
        /// </summary>
        internal static string ConverterAjdacencyList_JsonToGraph_WrongEdges {
            get {
                return ResourceManager.GetString("ConverterAjdacencyList_JsonToGraph_WrongEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane w pliku JSON - nie można zlokalizować &quot;id&quot; wieszchołków.
        /// </summary>
        internal static string ConverterAjdacencyList_JsonToGraph_WrongId {
            get {
                return ResourceManager.GetString("ConverterAjdacencyList_JsonToGraph_WrongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane w pliku JSON - nie można zlokalizować &quot;source&quot; krawędzi.
        /// </summary>
        internal static string ConverterAjdacencyList_JsonToGraph_WrongSource {
            get {
                return ResourceManager.GetString("ConverterAjdacencyList_JsonToGraph_WrongSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane w pliku JSON - nie można zlokalizować &quot;vertices&quot;.
        /// </summary>
        internal static string ConverterAjdacencyList_JsonToGraph_WrongVertices {
            get {
                return ResourceManager.GetString("ConverterAjdacencyList_JsonToGraph_WrongVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane w pliku JSON - nie można zlokalizować &quot;weight&quot; krawędzi.
        /// </summary>
        internal static string ConverterAjdacencyList_JsonToGraph_WrongWeight {
            get {
                return ResourceManager.GetString("ConverterAjdacencyList_JsonToGraph_WrongWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane w pliku JSON - nie można zlokalizować &quot;destination&quot; krawędzi.
        /// </summary>
        internal static string ConverterEdgeList_JsonToGraph_WrongDestination {
            get {
                return ResourceManager.GetString("ConverterEdgeList_JsonToGraph_WrongDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane w pliku JSON - nie można zlokalizować &quot;edge&quot;.
        /// </summary>
        internal static string ConverterEdgeList_JsonToGraph_WrongEdges {
            get {
                return ResourceManager.GetString("ConverterEdgeList_JsonToGraph_WrongEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane w pliku JSON - nie można zlokalizować &quot;source&quot; krawędzi.
        /// </summary>
        internal static string ConverterEdgeList_JsonToGraph_WrongSource {
            get {
                return ResourceManager.GetString("ConverterEdgeList_JsonToGraph_WrongSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane w pliku JSON - nie można zlokalizować &quot;weight&quot; krawędzi.
        /// </summary>
        internal static string ConverterEdgeList_JsonToGraph_WrongWeight {
            get {
                return ResourceManager.GetString("ConverterEdgeList_JsonToGraph_WrongWeight", resourceCulture);
            }
        }
    }
}
