//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace algorithmsRepresentation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("algorithmsRepresentation.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Sąsiedztwa.
        /// </summary>
        internal static string kind_adjacencyList {
            get {
                return ResourceManager.GetString("kind_adjacencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macierz Sąsiedztwa.
        /// </summary>
        internal static string kind_adjacencyMatrix {
            get {
                return ResourceManager.GetString("kind_adjacencyMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Krawędzi:.
        /// </summary>
        internal static string kind_edgeList {
            get {
                return ResourceManager.GetString("kind_edgeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graf Wierzchołkowy:.
        /// </summary>
        internal static string kind_vertexGraph {
            get {
                return ResourceManager.GetString("kind_vertexGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na początku porównamy impelementacje grafów i wyświetlimy je.
        ///.
        /// </summary>
        internal static string text_start {
            get {
                return ResourceManager.GetString("text_start", resourceCulture);
            }
        }
    }
}
